version: 1.0.{build}
image: Visual Studio 2017
configuration:
- Debug
- Release
build:
  verbosity: minimal
before_package:
- ps: Copy-Item C:\projects\StormHowlers\Base\$env:CONFIGURATION\Base.exe C:\projects\StormHowlers\Base\Game\.
artifacts:
- path: Base\Game
  name: Game
  type: WebDeployPackage
deploy:
- provider: GitHub
  description: AutoRelease
  auth_token:
    secure: xM32VMezbLuX5oOk+2PovegLK+XsbE23dsWldqjSHq5r2VoQH6lmpCW9sLTgMciif2NST12pu/OYLoPlxn2NSaAKAsu8IkdrKRnAle4stYc=
  draft: true